language: csharp
solution: Serpent.MessageBus/Serpent.MessageBus.sln
 
language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore Serpent.MessageBus/Serpent.MessageBus.sln
 - cd /home/travis/build/ErikRBergman/Serpent.MessageBus/Serpent.MessageBus/Serpent.MessageBus.Tests
 - dotnet xunit
 - cd /home/travis/build/ErikRBergman/Serpent.MessageBus/Serpent.MessageBus/Serpent.MessageHandlerChain.Tests
 - dotnet xunit

